### ISSUE TITLE
FxFlex not working when using *ngFor

### ISSUE THREAD

**Issue by whispertante** [ngbracket/ngx-layout#53] opened 2024-02-14 10:01 UTC
# Bug Report

#### What is the expected behaviour?
I have this layout with flexbox directives: 
```
<div fxLayout="row wrap">
  <div class="p-1" *ngFor="let addon of addons" fxFlex="33">
    <div>{{ addon.name }}</div>
  </div>
</div>

```
It should give each addon a width of 33% and wrap 4+ addons into the next line. 

#### What is the current behaviour?
It is instead not wrapping and shows all addons in 1 row. The fxFlex="33" is ignored. 
When I use pure flexbox HTML/CSS for this case, it works as expected: 

```
<style>
  .container {
    display: flex;
    flex-wrap: wrap;
    width: 100%;
  }
  .addon {
    width: 100%;
  }
  @media (min-width: 768px) { 
    .addon {
      width: 33%;
    }
  }
</style>

<div class="container">
  <div class="addon p-1" *ngFor="let addon of addons">
    <div>{{ addon.name }}</div>
  </div>
</div>
```

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://stackblitz.com/edit/flex-layout-seed-nightly) using the latest `npm` nightly release: 

#### Which versions of Angular, Material, OS, TypeScript, and browsers are affected?
Angular: 17.1.1
@ngbracket/ngx-layout: 17.0.1
tslib: 2.5.3

#### Is there anything else we should know?
In my example, addons is empty at page load and loaded afterwards.

**Comment by DuncanFaulkner** [comment] 2024-02-14 10:58
@whispertante thanks for reporting the issue - I'm looking to update to 17.1.1 shortly. I will check to see if this an issue with 17.0.1 or whether it has been introduced in 17.1.1 - either way will look into fixing it

**Comment by whispertante** [comment] 2024-02-15 11:46
@DuncanFaulkner I just downgraded to Angular 17.0.1 and there *ngFor is working.

**Comment by DuncanFaulkner** [comment] 2024-02-15 11:48
Ok looks like a recent change to angular might have caused the issue, will check

**Comment by walterkarabin** [comment] 2024-03-27 18:49
Hey @DuncanFaulkner I am also experiencing this issue. I am currently running 17.2.2, will you be making a fix for this?

**Comment by DuncanFaulkner** [comment] 2024-03-27 22:30
@walterkarabin sorry been tied up with a number of other things just recently and just not got round to looking into it, now 17.3 is out (and probably that's the last up date before 18 is released), I need to upgrade to 17.3 (locally) and find what's going on and then work on a fix.

**Comment by walterkarabin** [comment] 2024-04-01 19:00
@DuncanFaulkner Awesome, thanks for the reply! Any idea of a timeline as to when you will be working on that? Appreciate your help.

**Comment by DuncanFaulkner** [comment] 2024-04-03 11:51
@walterkarabin soon I've been preoccupied with other priorities recently, but should be back on the case

**Comment by DuncanFaulkner** [comment] 2024-04-17 07:16
@walterkarabin @whispertante 
I've been looking into the issue, and I just want to understand and see the problem, I've created a new stackblitz project as the one created by @whispertante seem to be using @angular/flex-layout and version 13 of Angular.

If you can use this project and show the issue then that would help me 

[Stackblitz-project](https://stackblitz.com/edit/stackblitz-starters-xsufnq?file=package.json)

Thanks
Duncan

**Comment by walterkarabin** [comment] 2024-04-19 22:20
Hey @DuncanFaulkner, I was able to reproduce the issue please see the stack blitz: [Flex-layout-bug (forked)](https://stackblitz.com/edit/stackblitz-starters-cw8xcv?file=src%2Fapp%2Fpage%2Fpage.component.html)

When using a selector for another component this seems to be where the fxFlex breaks down:
`<app-page style="outline: 1px solid green; padding: 2px" [data]="addons" fxLayout="row wrap" fxLayoutAlign="space-evenly"></app-page>`
I declare the selector with an `fxLayout` of `row wrap` and `fxLayoutAlign` of `space-evenly`

Am I correct in understanding that the selector should act as the container for its children? In other words, the styling of the selector should affect everything inside of it?

Thanks,
Walter

**Comment by DuncanFaulkner** [comment] 2024-07-19 06:56
@walterkarabin, I keep coming back to this issue as I want to try and resolve the issue you're having and I think I understand the issue. So for clarification you have set a selector with an fxLayout of row wrap and fxLayoutAlign of space-evenly, but in this you pass the data to another component that also has fxFlex="45" fxLayoutAlign="center center" applied. 

Yes the selector acts as a container and styling is passed down (as I understand it), but because you've applied styling on the receiving component as well (the one with fxFlex="45" fxLayoutAlign="center center") this will override the styling. Ultimately these directives are converted to inline styling in the DOM, and the specificity will naturally overwrite this.

if you remove the styling (the one with fxFlex="45" fxLayoutAlign="center center") then the space-evenly works as expected.

So I don't think there is an issue here and believe it's working as expected. 

Happy to discuss further if you think this is incorrect but will close this ticket as I think this is working as expected.

**Closed by DuncanFaulkner** 2024-07-19 06:56 UTC
